spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  security:
    jwt:
      secret: ${JWT_SECRET_PHRASE}
      expired: 3600000
  main:
    banner-mode: "off"
management:
  endpoint:
    web:
      exposure:
        include: health, info