spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profiler-db
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  security:
    cors:
      allowedOrigins: "*"
      allowedMethods: "*"
    jwt:
      secret: "profile"
      expired: 3600000

  main:
    banner-mode: "off"

